app: video-streaming-app
service: video-streaming-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  video_streaming_input: ${file(./Resources/lambda/video_streaming_input.yml)}
    
      