org: tahir1211
app: video-streaming-app
service: video-streaming-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.video_streaming_input
      